Traceback (most recent call last):
  File "experiment/experiment_s_p.py", line 160, in <module>
    ray.init()
  File "/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/ray/worker.py", line 696, in init
    _global_node = ray.node.Node(
  File "/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/ray/node.py", line 198, in __init__
    self.start_head_processes()
  File "/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/ray/node.py", line 800, in start_head_processes
    self.start_redis()
  File "/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/ray/node.py", line 568, in start_redis
    process_infos) = ray.services.start_redis(
  File "/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/ray/services.py", line 790, in start_redis
    redis_shard_port, p = _start_redis_instance(
  File "/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/ray/services.py", line 927, in _start_redis_instance
    raise RuntimeError("Couldn't start Redis. "
RuntimeError: Couldn't start Redis. Check log files: /tmp/ray/session_2020-11-07_09-08-04_989244_261058/logs/redis-shard_0.out /tmp/ray/session_2020-11-07_09-08-04_989244_261058/logs/redis-shard_0.err
