2020-11-14 13:47:51,253	INFO services.py:1164 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
Traceback (most recent call last):
  File "experiment/experiment_s_p.py", line 193, in <module>
    res = ray.get(futures)
  File "/home/akanji/miniconda3/envs/seldnian-pre/lib/python3.8/site-packages/ray/worker.py", line 1428, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(NameError): [36mray::run_experiment_p()[39m (pid=24681, ip=10.128.0.9)
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task
  File "experiment/experiment_s_p.py", line 135, in run_experiment_p
    uc_est = VanillaNN(X, y, test_size=exp['test_size'], stratify=stratify)
  File "/home/akanji/seldonian-fairness/seldonian/seldonian_nn.py", line 43, in __init__
    self.lagrange = Nones
NameError: name 'Nones' is not defined
